[package]
name = "pininorustless"
version = "0.1.0"
authors = ["gusdelact"]

[dependencies]
rustless = "0.10.0"
iron = "0.4"
url = "1"
valico = "1"
serde = "1.0.11"
serde_json = "1.0.2"
adaptadores = { path = "adaptadores" }
